name: Feature or Enhancement Request
description: Request a new feature or enhancement
labels: ["enhancement"]
title: "[FEAT]: "
body:
  - type: markdown
    attributes:
      value: |
        Before submitting your issue, please ensure that you have read our [Code of Conduct](https://github.com/alleyinteractive/.github/blob/main/CODE_OF_CONDUCT.md) and you have read through existing issues so as to avoid creating duplicates. 🙏 

  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the feature or enhancement you would like to see incorporated.
      placeholder: |
        e.g.
        I would like to see <...> incorporated into <...> so that <...> can be achieved.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Case
      description: Provide a detailed description of the use case for this feature/enhancement.
    validations:
      required: true
