name: Feature Request or Enhancement
description: Request a new feature or enhancement
labels: ["enhancement"]
title: "[FEAT]: "
body:
  - type: markdown
    attributes:
      value: |
        Before submitting your issue, please ensure that you have read our Contributor Code of Conduct and you have read through existing issues so as to avoid creating duplicates. 🙏 

  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the feature or enhancement you would like to see incorporated.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Case
      description: Provide detailed description of the use case for this feature/enhancement.
    validations:
      required: true
