name: PHP Coding Standards

on:
  workflow_call:
    inputs:
      php:
        default: 8.0
        required: false
        type: number

jobs:
  tests:
    runs-on: ubuntu-latest
    name: phpcs ${{ inputs.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Set up Composer caching
        uses: actions/cache@v3
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ inputs.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ inputs.php }}-composer-
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          tools: composer:v2
          coverage: none
      - name: Validate Composer
        run: composer validate --strict
      - name: Install dependencies
        uses: nick-invision/retry@v2.7.0
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install
      - name: Run phpcs
        run: composer run phpcs
